# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monoctl < Formula
  desc "CLI for Monoskope. AuthN & AuthZ for Kubernetes multi-cluster, multi-cloud environments."
  homepage "https://github.com/finleap-connect/monoctl"
  version "0.5.2-rev1"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/finleap-connect/monoctl/releases/download/v0.5.2-rev1/monoctl_osx_amd64.tar.gz"
      sha256 "a98a722c9620e9a76e1f55bc32871e6d101d82ad07198c46d0250e38ee5972b2"

      def install
        bin.install "monoctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/finleap-connect/monoctl/releases/download/v0.5.2-rev1/monoctl_osx_arm64.tar.gz"
      sha256 "e378edb43cdfad38bb3b4f97c495fe1a432c6dbed153a0cd66677bfeff1db570"

      def install
        bin.install "monoctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/finleap-connect/monoctl/releases/download/v0.5.2-rev1/monoctl_linux_arm64.tar.gz"
      sha256 "9ec7cdfc1acb42577065b3807810314078b54e0ace51a86834f54265220f0ee1"

      def install
        bin.install "monoctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/finleap-connect/monoctl/releases/download/v0.5.2-rev1/monoctl_linux_amd64.tar.gz"
      sha256 "ef60607b90ca3c379967070a5fb33feef1c64c8855783d2682f22d8c97468f75"

      def install
        bin.install "monoctl"
      end
    end
  end
end
